version: '3.7'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    container_name: elasticsearch
    environment:
      - discovery.seed_hosts=elasticsearch
      - cluster.name=docker-cluster
      - xpack.security.enabled=false  # Désactiver la sécurité pour simplifier le démarrage (à activer en production)
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.16.2
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.16.2
    container_name: filebeat
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /var/log/suricata:/var/log/suricata
    depends_on:
      - elasticsearch
    command: ./filebeat -e

  suricata:
    image: suricata/suricata
    container_name: suricata
    volumes:
      - ./suricata.yaml:/etc/suricata/suricata.yaml
      - ./rules:/etc/suricata/rules
    command: suricata -c /etc/suricata/suricata.yaml
    depends_on:
      - elasticsearch

volumes:
  elasticdata:
